/// <reference types="astro/client" />
/// <reference path="../.astro/types.d.ts" />
// This will be auto-generated by bknd when the app boots
/// <reference path="./bknd-types.d.ts" />

declare global {
  interface Window {
    // Add any globally accessible types here
  }
}

interface ImportMetaEnv {
  readonly DB_LIBSQL_URL: string;
  readonly DB_LIBSQL_TOKEN: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
